name: Deploy AWS Infrastructure with Terraform

on:
  push:
    branches:
      - main  # Change to the branch you want to use (e.g., master, dev)

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Specify the Terraform version you want to use

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2  # Use the latest version
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}   # Store your AWS Access Key ID in GitHub Secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   # Store your AWS Secret Access Key in GitHub Secrets
          aws-region: us-west-2  # Specify the region you want to use

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Validate Terraform configuration (optional but recommended)
      - name: Terraform Validate
        run: terraform validate

      # Apply Terraform configuration to create AWS resources
      - name: Terraform Apply
        run: terraform apply -auto-approve
